SRC_NAME = 
THISDIR = $(shell pwd)

all:

extract_test:

config_test:
clean:

romfs:
    $(ROMFSINST) -p +x $(THISDIR)/$(SRC_NAME)/zerotier-one /usr/bin/zerotier-one
    #$(ROMFSINST) $(THISDIR)/zerotier-one /usr/bin/zerotier-one
	$(ROMFSINST) $(THISDIR)/zerotier.sh /usr/bin/zerotier.sh

